"""User table cleanup

Revision ID: 858f95a575d4
Revises: b525627dcadf
Create Date: 2022-06-15 16:04:08.782113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858f95a575d4'
down_revision = 'b525627dcadf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
