"""Updates users table by removing unnecessary data leaving only id, name, user_id, email

Revision ID: b525627dcadf
Revises: 3cff761b14f7
Create Date: 2022-06-15 16:03:29.534568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b525627dcadf'
down_revision = '3cff761b14f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'floor')
    op.drop_column('users', 'seat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seat', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('floor', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gender', postgresql.ENUM('female', 'male', name='gender'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
